---
- name: Ensure AWS config dir exists
  file:
    state: directory
    path: ~/.aws

- name: Create AWS credentials file
  template:
    src: templates/aws_credentials.j2
    dest: ~/.aws/credentials
    mode: 0664
    backup: yes

- name: Create installation directory
  file:
    state: directory
    path: "{{ install_dir }}"

- name: Template out install-config.yaml file
  template:
    src: templates/install-config.yaml.j2
    dest: "{{ install_dir }}/install-config.yaml"

- name: Set platform facts for Mac OS
  set_fact:
    platform: mac
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Set platform facts for Linux
  set_fact:
    platform: linux
  when: ansible_facts['system'] == 'Linux'

- name: Install GNU Tar on Mac OS
  homebrew:
    name: gnu-tar
    state: latest
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Unarchive openshift-install binary
  unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-install-{{ platform }}.tar.gz"
    dest: "{{ installer_path }}"
    remote_src: yes
  become: true

- name: Unarchive openshift client binary
  unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-{{ platform }}.tar.gz"
    dest: "{{ installer_path }}"
    remote_src: yes
  become: true

- name: Run openshift-install
  command: "{{ installer_path }}/openshift-install create cluster --dir {{ install_dir }}"
  async: 3600
  poll: 0
  register: install_sleeper

- name: Check cluster installation completion
  async_status:
    jid: "{{ install_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 120
  delay: 30
