---

- name: Extract infrastructure informations
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: Infrastructure
  register: infrastructure

- name: Set infrastructure name
  set_fact:
    infrastructure_name: "{{ infrastructure.resources[0].status.infrastructureName }}"

- name: "Create OCS MachineSet on Zone {{ aws_region }}a"
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'ocs_machineset_zone_a.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: "Create OCS MachineSet on Zone {{ aws_region }}b"
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'ocs_machineset_zone_b.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: "Create OCS MachineSet on Zone {{ aws_region }}c"
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'ocs_machineset_zone_c.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: "Wait for OCS Machines bootstrap on Zone {{ aws_region }}a"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: MachineSet
    api_version: machine.openshift.io/v1beta1
    name: "{{ infrastructure_name }}-ocs-{{ aws_region }}a"
    namespace: openshift-machine-api
  register: machineset_a_status
  until: machineset_a_status.resources[0].status.availableReplicas is defined
  retries: 60
  delay: 10

- name: "Wait for OCS Machines bootstrap on Zone {{ aws_region }}b"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: MachineSet
    api_version: machine.openshift.io/v1beta1
    name: "{{ infrastructure_name }}-ocs-{{ aws_region }}b"
    namespace: openshift-machine-api
  register: machineset_b_status
  until: machineset_b_status.resources[0].status.availableReplicas is defined
  retries: 60
  delay: 10

- name: "Wait for OCS Machines bootstrap on Zone {{ aws_region }}c"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: MachineSet
    api_version: machine.openshift.io/v1beta1
    name: "{{ infrastructure_name }}-ocs-{{ aws_region }}c"
    namespace: openshift-machine-api
  register: machineset_c_status
  until: machineset_c_status.resources[0].status.availableReplicas is defined
  retries: 60
  delay: 10

- name: Create openshift-storage namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'ocs_namespace.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Create OCS OperatorGroup
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'ocs_operatorgroup.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Create OCS Operator Subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'ocs_subscription.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

# TODO: check for operator install completion

- name: "Wait for StorageCluster CRD"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: CustomResourceDefinition
    api_version: apiextensions.k8s.io/v1
    name: storageclusters.ocs.openshift.io
  register: storagecluster_crd
  until: 
    - storagecluster_crd.resources | length > 0
  retries: 60
  delay: 10

- name: "Create OCS StorageCluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'ocs_storagecluster.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: "Wait for OCS StorageCluster Provisioning"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: StorageCluster
    api_version: ocs.openshift.io/v1
    name: "ocs-storagecluster"
    namespace: openshift-storage
  register: storagecluster_status
  until: 
    - storagecluster_status.resources[0].status is defined
    - storagecluster_status.resources[0].status.phase == 'Ready'
  retries: 60
  delay: 10
