---
- name: Create Jaeger Operator Subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'jaeger_subscription.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Create Kiali Operator Subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'kiali_subscription.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Create Service Mesh Operator Subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'servicemeshoperator_subscription.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Create istio-system namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'istio_namespace.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Wait for ServiceMesh Control Plane CRD
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: CustomResourceDefinition
    api_version: apiextensions.k8s.io/v1
    name: servicemeshcontrolplanes.maistra.io
  register: servicemeshcontrolplane_crd
  until: 
    - servicemeshcontrolplane_crd.resources | length > 0
  retries: 60
  delay: 10

- name: Create basic Service Mesh Control Plane
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'servicemeshcontrolplane-basic.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360
